# Generated by Django 2.2.3 on 2019-07-08 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome:')),
                ('mae', models.CharField(blank=True, max_length=30, null=True, verbose_name='Mãe:')),
                ('logradouro', models.CharField(max_length=60, verbose_name='Nome da rua:')),
                ('numero', models.IntegerField(verbose_name='Número:')),
                ('complemento', models.CharField(blank=True, max_length=30, null=True, verbose_name='Complemento:')),
                ('bairro', models.CharField(blank=True, max_length=30, null=True, verbose_name='Bairro')),
                ('lotacao', models.CharField(choices=[('BM', 'Bombeiro Miliar'), ('PM', 'Policia Miliar')], max_length=2, verbose_name='Lotado em:')),
                ('matricula', models.CharField(max_length=8, verbose_name='Nr policia/Bombeiro')),
                ('data_nascimento', models.DateField(verbose_name='Data nascimento:')),
                ('observacoe', models.TextField(max_length=1600, verbose_name='Observações:')),
            ],
        ),
        migrations.CreateModel(
            name='Dependentes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome dependente:')),
                ('parentesco', models.CharField(choices=[('FILHO(A)', 'Filho(a)'), ('ENTEADO(A)', 'Enteado(a)'), ('OUTROS', 'Outros')], max_length=10, verbose_name='Relacionamento com titular:')),
                ('data_nascimento', models.DateField(verbose_name='Data nascimento:')),
                ('observacoe', models.TextField(max_length=1600, verbose_name='Observações:')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publico.Publico')),
            ],
        ),
    ]
