# Generated by Django 2.2.3 on 2019-07-08 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publico', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dependentes',
            old_name='observacoe',
            new_name='observacoes',
        ),
        migrations.RenameField(
            model_name='publico',
            old_name='observacoe',
            new_name='observacoes',
        ),
        migrations.AlterField(
            model_name='publico',
            name='numero',
            field=models.CharField(max_length=6, verbose_name='Número:'),
        ),
    ]
