# Generated by Django 2.2.3 on 2019-07-16 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_auto_20190715_2144'),
        ('publico', '0003_auto_20190715_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_locado', models.DateField()),
                ('data_devolucao', models.DateField()),
                ('observacao', models.TextField()),
                ('locador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publico.Publico')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.Material')),
            ],
        ),
    ]
