# Generated by Django 2.2.3 on 2019-07-16 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publico', '0004_locacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locacao',
            name='observacao',
            field=models.TextField(blank=True, max_length=1600, verbose_name='Observações:'),
        ),
    ]
