# Generated by Django 2.2.3 on 2019-07-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publico', '0005_auto_20190715_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='publico',
            name='email',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Email:'),
        ),
        migrations.AddField(
            model_name='publico',
            name='telefone',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Telefone:'),
        ),
        migrations.AlterField(
            model_name='publico',
            name='bairro',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Bairro:'),
        ),
        migrations.AlterField(
            model_name='publico',
            name='lotacao',
            field=models.CharField(choices=[('BM', 'Bombeiro Miliar'), ('PM', 'Policia Miliar'), ('OUTROS', 'Outros')], max_length=2, verbose_name='Lotado em:'),
        ),
    ]
