# Generated by Django 2.2.3 on 2019-07-20 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publico', '0006_auto_20190716_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locacao',
            old_name='tipo',
            new_name='material',
        ),
        migrations.AlterField(
            model_name='locacao',
            name='observacao',
            field=models.TextField(blank=True, max_length=800, verbose_name='Observações:'),
        ),
    ]
