# Generated by Django 2.2.3 on 2019-07-20 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publico', '0007_auto_20190720_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publico',
            old_name='telefone',
            new_name='telefone1',
        ),
        migrations.AddField(
            model_name='publico',
            name='telefone2',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Telefone:'),
        ),
    ]
