# Generated by Django 2.2.3 on 2019-07-16 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='observacoes',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Observações do material:'),
        ),
    ]
