# Generated by Django 2.2.3 on 2019-07-16 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_auto_20190715_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='locado',
            field=models.BooleanField(default=False, verbose_name='Locado:'),
        ),
    ]
